### ISSUE TITLE
Angle-conversion functions shouldn't be template

### ISSUE THREAD

**Issue by pdigiglio** [yap/YAP#129]
I found a pretty nasty bug:
```cpp
std::cout << yap::rad(30)  << std::endl;
std::cout << yap::rad(30.) << std::endl;
std::cout << yap::rad(45)  << std::endl;
std::cout << yap::rad(45.) << std::endl;
```
outputs
```
0
0.523599
0
0.785398
```

I think `pi()` should definitely return a `double`. So should some other functions such as, e.g., `rad()` and `deg()`.

**Comment by greenwald** [comment]
It's not a bug. But true, it's overkill to template them.
