### ISSUE TITLE
Fix freeAmplitudes of single DecayChannels

### ISSUE THREAD

**Issue by Jojosito** [yap/YAP#27]
Free amplitudes of DecayChannels that are the only DecayChannels of their DecayingParticles should be "fixed" by default.

**Comment by greenwald** [comment]
If there's only one free amplitude, yes, it's arbitrary. But we shouldn't remove it.

**Comment by greenwald** [comment]
When a decaying particle has only one possible decay channel, yes, we should fix the free amplitude of the decay channel (initialized to 1).

**Comment by Jojosito** [comment]
Done
