### ISSUE TITLE
Compiler option -fdiagnostics-color=

### ISSUE THREAD

**Issue by pdigiglio** [yap/YAP#32]
Regarding the `-fdiagnostics-color=` flag in the pull request #31, it was introduced in _GCC_ since version 4.9. Should we keep it and require the user to have such a version? Should we remove it completely? Should we check in the _CMakeLists.txt_ the compiler version and set the flags accordingly?

**Comment by greenwald** [comment]
Considering it's only for the cosmetic appearance of the output, it's not necessary. Leave it disabled. If you want to write something that checks its availability and conditionally turns it on, sure, go ahead. But to require a particular GCC version for something superficial is overkill.

**Comment by pdigiglio** [comment]
I won't do that, then. We can keep the option commented in the remote repository and uncomment it in our local ones if we want it.
